### ISSUE TITLE
Ordered list formatting is busted

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#143]
![image](https://user-images.githubusercontent.com/160754/182028539-76eea0bf-bae9-4a32-b150-4e2e0ec57a2e.png)

**Comment by TLSM** [comment]
Root cause of this on the upstream was the Markdown engine turning ordered list items into `<li><p>foo</p></li>`, where the `<p>` would display as a block element, if I recall correctly.

My solution there, largely out of need for backwards compatibility with a ~year of post & comment `body_html` generated with the paragraph elements, was to instead fix the clientside display of the paragraphs to prevent wrapping. See: https://github.com/TLSM/rDrama/commit/b5e09444c012637c94491a3b69cbe2f0204fdb56 — main.css:
```css
/* Fix for <ol> being populated with <li><p></p></li> in many contexts. */
.post-body li > p:first-child,
.comment-text li > p:first-child,
.preview li > p:first-child,
div[id^="form-preview-"] li > p:first-child,
div[id^="reply-edit-"] li > p:first-child {
	display: inline;
}
```

Given y'all are setting up a new site without the improperly generated existing content, it may be worth instead coercing `sanitize(⋅)` into not generating the paragraph tags.
