### ISSUE TITLE
Small changes to the midnight theme css. 

### ISSUE THREAD

**Issue by beigexperience** [themotte/rDrama#738]
Can you please add these to the midnight theme? 

```CSS
.volunteer_teaser {background-color: transparent;}
html{overflow-x:hidden;}

img[src^="https://www.themotte.org/assets/images/TheMotte/default"],
img[src^="https://www.themotte.org/assets/images/default_"]{
	filter: invert(1);
}

.container{
	margin: 10px!important;
}
```
